# Generated by Django 2.1.7 on 2020-02-12 16:31

import Account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_first_name', models.CharField(default='', max_length=30)),
                ('profile_last_name', models.CharField(default='', max_length=30)),
                ('hospital', models.CharField(default='None', max_length=50)),
                ('adress_hospital', models.CharField(default='None', max_length=60)),
                ('phone_number', models.IntegerField(default='1')),
                ('caption', models.TextField(default='', max_length=750)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/profile_images')),
                ('buletin_picture', models.ImageField(blank=True, null=True, upload_to='images/buletin')),
            ],
            options={
                'ordering': ('profile_first_name', 'profile_last_name'),
            },
        ),
        migrations.CreateModel(
            name='PacientProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_first_name', models.CharField(default='', max_length=30)),
                ('profile_last_name', models.CharField(default='', max_length=30)),
                ('cnp', models.IntegerField(default='0')),
                ('phone_number', models.CharField(default='1', max_length=20)),
                ('caption', models.TextField(default='', max_length=750)),
                ('blood_transfuzion', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/profile_images')),
                ('buletin_picture', models.ImageField(blank=True, null=True, upload_to='images/buletin')),
                ('analize', models.FileField(blank=True, null=True, upload_to='pdf_pacient/')),
            ],
            options={
                'ordering': ('profile_first_name', 'profile_last_name'),
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=50)),
                ('is_pacient', models.BooleanField(default='True', verbose_name='pacient')),
                ('is_doctor', models.BooleanField(default='False', verbose_name='doctor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', Account.models.MilanoUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='pacientprofileuser',
            name='profile_pacient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofileuser',
            name='profile_doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
